import * as THREE from 'three'
import { createGLB } from './glbExport.js'
import { generateInstanceSpec as generateSpec, canConvertToInstanceSpec } from './InstanceSpecGenerator.js'
import { estimateDrawCalls } from '../schemas/instanceSpec.js'
import { validateAnalysis } from './isolated/protocol.js'

/**
 * Map of addon names to their import paths
 */
const ADDON_IMPORTS = {
  Water: "import { Water } from 'three/examples/jsm/objects/Water.js'",
  Water2: "import { Water as Water2 } from 'three/examples/jsm/objects/Water2.js'",
  Sky: "import { Sky } from 'three/examples/jsm/objects/Sky.js'",
  Reflector: "import { Reflector } from 'three/examples/jsm/objects/Reflector.js'",
  SimplexNoise: "import { SimplexNoise } from 'three/examples/jsm/math/SimplexNoise.js'"
}

/**
 * Detect which addons are used in the code
 * @param {string} code - The generated code
 * @returns {string[]} - Array of addon names used
 */
export function detectUsedAddons(code) {
  const used = []
  
  // Check for direct addon class usage
  if (/\baddons\.Water\b/.test(code) && !/\baddons\.Water2\b/.test(code.split('addons.Water2').join(''))) {
    used.push('Water')
  }
  if (/\baddons\.Water2\b/.test(code)) {
    used.push('Water2')
  }
  if (/\baddons\.Sky\b/.test(code)) {
    used.push('Sky')
  }
  if (/\baddons\.Reflector\b/.test(code)) {
    used.push('Reflector')
  }
  if (/\baddons\.SimplexNoise\b/.test(code)) {
    used.push('SimplexNoise')
  }
  
  // Check for helper functions that use specific addons
  if (/\baddons\.createSkyWithSun\b/.test(code) && !used.includes('Sky')) {
    used.push('Sky')
  }
  if (/\baddons\.createWaterPlane\b/.test(code) && !used.includes('Water')) {
    used.push('Water')
  }
  
  return [...new Set(used)]
}

/**
 * Generate import statements for used addons
 * @param {string[]} usedAddons - Array of addon names
 * @returns {string} - Import statements
 */
export function generateAddonImports(usedAddons) {
  if (!usedAddons || usedAddons.length === 0) {
    return ''
  }
  
  const imports = usedAddons
    .filter(addon => ADDON_IMPORTS[addon])
    .map(addon => ADDON_IMPORTS[addon])
  
  return imports.join('\n')
}

/**
 * Export a THREE.Object3D as a GLB file
 * @param {THREE.Object3D} object - The object to export
 * @param {string} filename - Base filename (without extension)
 */
export async function exportAsGLB(object, filename = 'asset') {
  downloadGLB(await createGLB(object), filename)
}

/**
 * Export a THREE.Object3D as a GLB with animations
 * @param {THREE.Object3D} object - The object to export
 * @param {THREE.AnimationClip[]} clips - Animation clips to include
 * @param {string} filename - Base filename
 */
export async function exportAsAnimatedGLB(object, clips, filename = 'asset') {
  downloadGLB(await createGLB(object, { animations: clips }), filename)
}

export function downloadGLB(gltf, filename) {
  const url = URL.createObjectURL(new Blob([gltf], { type: 'application/octet-stream' }))
  try {
    const link = document.createElement('a')
    link.href = url
    link.download = `${filename}.glb`
    link.click()
  } finally {
    URL.revokeObjectURL(url)
  }
}

/**
 * Generate a code snippet for instantiating the asset
 * @param {Object} spec - The asset specification
 * @returns {string}
 */
export function generateCodeSnippet(spec) {
  const specJson = JSON.stringify(spec, null, 2)
  
  return `// Asset generated by ThreeJS Generator
// Generator: ${spec.generator}
// Seed: ${spec.seed}

import { createAsset } from 'threejs-generator/runtime';

// Asset specification
const spec = ${specJson};

// Create the asset
const asset = createAsset(spec);

// Add to your scene
scene.add(asset.root);

// If the asset has animations, call tick in your render loop:
if (asset.tick) {
  function animate() {
    requestAnimationFrame(animate);
    const delta = clock.getDelta();
    const elapsed = clock.getElapsedTime();
    asset.tick(elapsed, delta);
    renderer.render(scene, camera);
  }
  animate();
}

// Remember to dispose when done:
// asset.dispose();
`
}

/**
 * Generate a standalone vanilla JS code snippet
 * @param {Object} spec - The asset specification
 * @param {string} generatorCode - The generator source code
 * @returns {string}
 */
export function generateStandaloneSnippet(spec, generatorCode) {
  return `// Standalone ThreeJS Asset
// Generated by ThreeJS Generator

import * as THREE from 'three';

${generatorCode}

// Asset specification
const spec = ${JSON.stringify(spec, null, 2)};

// Create and use the asset
export function createAsset() {
  return ${spec.generator}Generator(spec.params, spec.seed);
}
`
}

/**
 * Generate a portable code snippet for Creative/Procedural mode assets
 * Includes necessary addon imports and setup code
 * @param {string} code - The generated createAsset function code
 * @param {string[]} usedAddons - Array of addon names used
 * @param {object} options - Additional options
 * @returns {string} - Complete portable code
 */
export function generateCreativeCodeSnippet(code, usedAddons = [], options = {}) {
  const { seed = 12345, hasAnimation = false } = options
  
  // Generate addon imports
  const addonImports = generateAddonImports(usedAddons)
  
  // Generate addon setup code if needed
  let addonSetup = ''
  if (usedAddons.length > 0) {
    addonSetup = `
// Setup addons object (replicate the runtime environment)
const addons = {
  ${usedAddons.includes('Water') ? 'Water,' : ''}
  ${usedAddons.includes('Water2') ? 'Water2,' : ''}
  ${usedAddons.includes('Sky') ? 'Sky,' : ''}
  ${usedAddons.includes('Reflector') ? 'Reflector,' : ''}
  ${usedAddons.includes('SimplexNoise') ? 'SimplexNoise,' : ''}
  textures: {
    // You may need to create a water normals texture
    // See: https://threejs.org/examples/#webgl_shaders_ocean
    waterNormals: null // Replace with your water normals texture
  }
};
`.trim()
  }

  // Build the complete snippet
  let snippet = `// Creative Mode Asset
// Generated by ThreeJS Generator
// ${usedAddons.length > 0 ? `Uses addons: ${usedAddons.join(', ')}` : 'No addons required'}

import * as THREE from 'three';
${addonImports}
${addonSetup}

// Generated asset factory
${code}

// Usage example:
const seed = ${seed};
const textures = {}; // Add any textures here
const params = {};   // Add any parameter overrides here
${usedAddons.length > 0 ? '' : '// const addons = null; // No addons needed'}

const asset = createAsset(THREE, seed, textures, params${usedAddons.length > 0 ? ', addons' : ''});

// Add to your scene
scene.add(asset.root);
`

  if (hasAnimation) {
    snippet += `
// Animation loop (asset has runtime animation)
const clock = new THREE.Clock();
function animate() {
  requestAnimationFrame(animate);
  const delta = clock.getDelta();
  const elapsed = clock.getElapsedTime();
  
  // Update asset animation
  if (asset.update) {
    asset.update(elapsed, delta);
  }
  
  renderer.render(scene, camera);
}
animate();
`
  }

  snippet += `
// Cleanup when done:
// asset.dispose();
`

  return snippet
}

/**
 * Generate minimal code for clipboard copy (just the function)
 * @param {string} code - The createAsset function code
 * @param {string[]} usedAddons - Array of addon names used  
 * @returns {string}
 */
export function generateMinimalCodeSnippet(code, usedAddons = []) {
  let header = '// ThreeJS Generator - Creative Mode Asset\n'
  
  if (usedAddons.length > 0) {
    header += `// Required addon imports:\n`
    usedAddons.forEach(addon => {
      if (ADDON_IMPORTS[addon]) {
        header += `// ${ADDON_IMPORTS[addon]}\n`
      }
    })
    header += '\n'
  }
  
  return header + code
}

// -----------------------------------------
// Instance Specification Export Functions
// -----------------------------------------

/**
 * Generate an Instance Specification from createAsset code
 * This format enables batching for minimal draw calls when used in a world generator
 * 
 * @param {string} code - The createAsset function code
 * @param {Object} options - Generation options
 * @param {string} options.name - Name for the asset
 * @param {string} options.prompt - Original prompt used to generate the asset
 * @param {number} options.seed - Seed used for generation
 * @param {Object} options.params - Parameters used
 * @returns {Promise<Object>} - The instance specification
 */
export async function generateInstanceSpecFromCode(code, options = {}) {
  return generateSpec(code, options)
}

/**
 * Check if code can be converted to an instance specification
 * @param {string} code - The createAsset function code
 * @returns {{ valid: boolean, reason: string, recommendation?: string }}
 */
export function checkBatchingSupport(code) {
  return canConvertToInstanceSpec(code)
}

/**
 * Estimate draw call savings from batching
 * @param {Object} spec - The instance specification
 * @param {number} placementCount - Expected number of placements in world
 * @returns {{ batched: number, unbatched: number, savings: string }}
 */
export function estimateBatchingSavings(spec, placementCount = 100) {
  const { batched, unbatched } = estimateDrawCalls(spec, placementCount)
  const savingsPercent = ((unbatched - batched) / unbatched * 100).toFixed(1)
  
  return {
    batched,
    unbatched,
    savings: `${savingsPercent}% reduction (${unbatched} -> ${batched} draw calls)`
  }
}

/**
 * Export an Instance Specification as a JSON file
 * @param {Object} spec - The instance specification
 * @param {string} filename - Base filename (without extension)
 */
export async function exportAsInstanceSpec(spec, filename = 'asset') {
  const json = JSON.stringify(spec, null, 2)
  const blob = new Blob([json], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  
  const link = document.createElement('a')
  link.href = url
  link.download = `${filename}.instancespec.json`
  link.click()
  
  URL.revokeObjectURL(url)
}

/**
 * Generate a complete batchable export package
 * Includes both the instance spec and the original code for fallback
 * @param {string} code - The createAsset function code
 * @param {Object} options - Export options
 * @returns {Promise<string>} - Combined export content
 */
export async function generateBatchableExport(code, options = {}) {
  const {
    name = 'Batchable Asset',
    prompt = '',
    seed = 12345,
    params = {},
    textures = {}
  } = options
  
  // Generate the instance specification
  const spec = options.instanceSpec
    ? validateAnalysis(options.instanceSpec)
    : await generateSpec(code, { name, prompt, seed, params, textures })
  
  // Create combined export with both spec and original code
  const exportContent = `/**
 * Batchable Asset Export
 * Generated by ThreeJS Generator
 * 
 * This file contains both:
 * 1. Instance Specification (for batched rendering)
 * 2. Original createAsset code (for standalone use)
 * 
 * Usage in World Generator:
 *   import spec from './asset.batchable.js'
 *   batchedRenderer.addFromSpec(spec.instanceSpec, positions)
 * 
 * Standalone usage:
 *   import { createAsset } from './asset.batchable.js'
 *   const asset = createAsset(THREE, seed, textures, params)
 */

// Instance Specification for batched rendering
export const instanceSpec = ${JSON.stringify(spec, null, 2)};

// Original createAsset function for standalone use
${code}

// Export both for flexibility
export default {
  instanceSpec,
  createAsset: typeof createAsset !== 'undefined' ? createAsset : null
};
`
  
  return exportContent
}

/**
 * Export a batchable asset file (combined spec + code)
 * @param {string} code - The createAsset function code
 * @param {Object} options - Export options
 * @param {string} filename - Base filename
 */
export async function exportAsBatchableAsset(code, options = {}, filename = 'asset') {
  try {
    const content = await generateBatchableExport(code, options)
    const blob = new Blob([content], { type: 'text/javascript' })
    const url = URL.createObjectURL(blob)
    
    const link = document.createElement('a')
    link.href = url
    link.download = `${filename}.batchable.js`
    link.click()
    
    URL.revokeObjectURL(url)
    
    return { success: true }
  } catch (error) {
    console.error('[Exporter] Failed to generate batchable export:', error)
    return { success: false, error: error.message }
  }
}
