import { test, expect } from '@playwright/test';
import { advanceFrames, loadWithClock } from './clock.js';

test('real keyboard input lifts, delivers, pauses, and starts a fresh round', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await loadWithClock(page);
  await expect(page.getByRole('button', { name: 'Let’s snack' })).toBeEnabled();
  await expect(page.locator('canvas')).toBeVisible();
  await page.getByRole('button', { name: 'Let’s snack' }).click();
  await page.getByRole('button', { name: 'Mute sound', exact: true }).click();
  await expect(page.locator('canvas')).toBeFocused();
  await page.keyboard.down('Space');
  await advanceFrames(page, 350);
  await expect(page.locator('#hint-text')).toContainText('Bring it to your mug');
  await page.keyboard.down('KeyW');
  await advanceFrames(page, 1400);
  await page.keyboard.up('KeyW');
  await page.keyboard.up('Space');
  await advanceFrames(page, 50);
  await expect(page.locator('#score')).toHaveText('100');
  await expect(page.locator('#saved')).toHaveText('1');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toBeVisible();
  const time = await page.locator('#time').textContent();
  await advanceFrames(page, 1100);
  await expect(page.locator('#time')).toHaveText(time);
  await page.getByRole('button', { name: 'Back to the snacks', exact: true }).click();
  await expect(page.locator('#app')).toHaveAttribute('data-phase', 'playing');
  await expect(page.locator('canvas')).toBeFocused();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Start a fresh round' }).click();
  await advanceFrames(page, 16);
  await expect(page.locator('#score')).toHaveText('0');
  await expect(page.locator('#saved')).toHaveText('0');
  await expect(page.locator('#time')).toHaveText('1:30');
  await expect(page.locator('#app')).toHaveAttribute('data-phase', 'playing');
  expect(errors).toEqual([]);
});

test('a complete round ends and replay resets; focus stays inside the result dialog', async ({ page }) => {
  test.setTimeout(120000);
  await page.setViewportSize({ width: 640, height: 480 });
  await loadWithClock(page);
  await page.getByRole('button', { name: 'Let’s snack' }).click();
  await advanceFrames(page, 89200);
  await expect(page.locator('#app')).toHaveAttribute('data-phase', 'playing');
  await expect(page.locator('#time')).toHaveText('0:01');
  await advanceFrames(page, 1000);
  await expect(page.locator('#app')).toHaveAttribute('data-phase', 'ended');
  await expect(page.locator('#result-overlay')).toBeVisible();
  await expect(page.locator('#time')).toHaveText('0:00');
  await expect(page.locator('#replay-button')).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  await expect(page.locator('#home-button')).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(page.locator('#replay-button')).toBeFocused();
  await page.getByRole('button', { name: 'One more bite' }).click();
  await expect(page.locator('#app')).toHaveAttribute('data-phase', 'playing');
  await advanceFrames(page, 32);
  await expect(page.locator('#score')).toHaveText('0');
  await expect(page.locator('#saved')).toHaveText('0');
  await expect(page.locator('#time')).toHaveText('1:30');
  await expect(page.locator('canvas')).toBeFocused();
});

test('small-screen layout has reachable controls and touch beam picks up a snack', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await loadWithClock(page);
  await page.getByRole('button', { name: 'Let’s snack' }).click();
  const beam = page.locator('#touch-beam');
  await expect(beam).toBeVisible();
  await expect(page.getByRole('button', { name: 'Fly up', exact: true })).toBeVisible();
  const bounds = await beam.boundingBox();
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  await page.mouse.down();
  await advanceFrames(page, 350);
  await expect(page.locator('#hint-text')).toContainText('Bring it to your mug');
  await page.mouse.up();
  await advanceFrames(page, 50);
  await expect(page.locator('#hint-text')).toContainText('Snack dropped');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile-playing.png' });
});
